name: ej1-workflow

on: 
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Bajar codigo
            uses: actions/checkout@v4

          - name: Accion Node
            uses: actions/setup-node@v4
            
          - name: Ejecutar comandos
            run: |
                npm i
                npm test
                
          - name: Construir imagen
            uses: cloudposse/github-action-docker-compose-test-run@main
